declare var __TSGID: string
declare var __AUTHURL: string
declare var __CLIENT_ID: string
declare var __CLIENT_SECRET: string
declare var __ACCESS_TOKEN: string
declare var __EXPIRATION_TIME: number
declare var __BASE_URL: string
declare var __pageSize: number
declare var __READ_ALL_TENANTS: boolean
declare var __USER_PAUSE: number